
---
- hosts: test-pg
  become: true
  become_method: sudo
  remote_user: alf

  tasks:
      
  - name: "Installasjon av diverse pakker"
    apt: 
      name: ['open-vm-tools']
      state: latest

  - name: Installasjon av pakke realmd
    apt:
      name: ['realmd']
      state: latest

  - name: Installasjon av pakke oddjob
    apt:
      name: ['oddjob']
      state: latest

  - name: Installasjon av pakke oddjob-mkhomedir
    apt:
      name: ['oddjob-mkhomedir']
      state: latest

  - name: Installasjon av pakke sssd
    apt:
      name: ['sssd']
      state: latest

  - name: Installasjon av pakke samba-common
    apt:
      name: ['samba-common']
      state: latest

  - name: Installasjon av pakke adcli
    apt:
      name: ['adcli']
      state: latest

  - name: Installasjon av pakke vim
    apt:
      name: ['vim']
      state: latest

  - name: Installasjon av pakke vim-common
    apt:
      name: ['vim-common']
      state: latest

  - name: Installasjon av pakke vim-asciidoc
    apt:
      name: ['vim-asciidoc']
      state: latest


  - name: Installasjon av pakke gcc
    apt:
      name: ['gcc']
      state: latest

  - name: Installasjon av pakke nfs-kernel-server
    apt:
      name: ['nfs-kernel-server']
      state: latest

  - name: Installasjon av pakke bash-completion
    apt:
      name: ['bash-completion']
      state: latest

  - name: Installasjon av pakke rsync
    apt:
      name: ['rsync']
      state: latest

  - name: Installasjon av pakke chrony
    apt:
      name: ['chrony']
      state: latest

  - name: Installasjon av pakke nrpe-ng
    apt:
      name: ['nrpe-ng']

  - name: Installasjon av pakke nagios-nrpe-server
    apt:
      name: ['nagios-nrpe-server']
      state: latest

  - name: Installasjon av pakke nagios-plugins
    apt:
      name: ['nagios-plugins']
      state: latest
