
---
- hosts: dvh9
  become: true
  become_method: sudo
  remote_user: alf

  tasks:
    - name: "Update packages and upgrade"
      apt:
        update_cache: true
        upgrade: dist
        force_apt_get: true

    - name: "Install PostgreSQL 12 packages"
      apt:
        name: ['postgresql-14','pgtop','check-pgactivity', 'pg-activity', 'pgagent', 'postgresql-14-postgis-3','postgresql-contrib']
        state: latest

